version: '2'

services:
  mysql:
    image: mysql:5.6
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  mysqltest:
    image: mysql:5.6
    ports: 
      - "${MYSQL_TEST_PORT}:3306"
    volumes:
      - db_data_test:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_DB_PASSWORD}
      MYSQL_DATABASE: ${TEST_DB_NAME}

  php:
    build:
      context: .
      dockerfile: /etc/docker/php
    restart: always
    volumes:
      - ./:/www

  web:
    build:
      context: .
      dockerfile: /etc/docker/nginx
    volumes:
      - ./:/www
      - ./etc/conf/hosts.conf:/etc/nginx/conf.d/site.conf
      - ./etc/ssl/server.crt:/etc/nginx/ssl/server.crt
      - ./etc/ssl/server.key:/etc/nginx/ssl/server.key
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    restart: always
    links:
      - php
      - mysql

volumes:
  db_data:
