version: '2'

services: 
  mysql:
    image: mysql:5.6
    ports: 
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_seed

  httpd: 
    build:
      context: .
      dockerfile: /etc/docker/server
    volumes:
      - ./:/var/www/html
      - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    restart: always
    links:
      - mysql
      
volumes:
  db_data:
